### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by londumas** [open-mmlab/mmrotate#788]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

using master

### Reproduces the problem - code sample

Train `rotated_reppoints_r50_fpn_1x_dota_le135.py`

### Reproduces the problem - command or script

Using rotated_reppoints_r50_fpn_1x_dota_le135.py

### Reproduces the problem - error message

```
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by londumas** [comment]
The following line 
https://github.com/open-mmlab/mmrotate/blob/7755aa53b6e2d9c61fd765e67a60daa7ed8a1e05/mmrotate/core/bbox/assigners/convex_assigner.py#L119
should be replaced by:
`points_range = torch.arange(points.shape[0], dtype=torch.long, device=points_lvl.device) `

**Comment by yangxue0827** [comment]
Fixed in https://github.com/open-mmlab/mmrotate/pull/784

**Comment by londumas** [comment]
> Fixed in #784

Thanks @yangxue0827, however not fixed there https://github.com/open-mmlab/mmrotate/blob/d80310aa2c4a67c877c62432cddee246d2a4dbcd/mmrotate/core/bbox/assigners/convex_assigner.py#L119

**Comment by londumas** [comment]
Sorry, I meant, not fixed in main, thanks. I will be waiting for main to be updated and I will close the bug repport.

**Comment by londumas** [comment]
And the same error is there:

https://github.com/open-mmlab/mmrotate/blob/d92844abf9af8fe6c281f3196020003bb20a38b8/mmrotate/models/task_modules/assigners/rotated_atss_assigner.py#L194

and there

https://github.com/open-mmlab/mmrotate/blob/d92844abf9af8fe6c281f3196020003bb20a38b8/mmrotate/models/task_modules/assigners/sas_assigner.py#L179

> I see, can you propose a PR to fix this bug.

sorry, but I can not.
